version: "3.9"

networks:
    gocanto:
        name: "gocanto"
        driver: "bridge"

volumes:
    database:

services:
    server:
        image: "golang:latest"
        restart: "always"
        env_file:
            - .env
        ports:
            - "127.0.0.1:8080:8080"
        networks:
            - gocanto
        build:
            context: .
            dockerfile: ./app/Dockerfile
        logging:
            driver: "json-file"
            options:
                max-size: "10M"
                max-file: "20"

    db:
        image: "postgres:${POSTGRES_VERSION}"
        restart: always
        env_file:
            - .env
        ports:
            - "127.0.0.1:5432:5432"
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DATABASE}
        networks:
            - gocanto
        logging:
            driver: "json-file"
            options:
                max-size: "10M"
                max-file: "20"
        volumes:
            - ./database/data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
            interval: 5s
            timeout: 5s
            retries: 5
