version: "3.9"

networks:
    gocanto:
        name: gocanto
        driver: bridge

volumes:
    database:

services:
    postgres:
        container_name: gocanto-db
        image: "postgres:${POSTGRES_DOCKER_VERSION}"
        restart: always
        env_file:
            - .env
        ports:
            - "127.0.0.1:5432:5432"
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DATABASE}
        networks:
            - gocanto
        logging:
            driver: "json-file"
            options:
                max-size: "10M"
                max-file: "20"
        volumes:
            - ./database/data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
            interval: 5s
            timeout: 5s
            retries: 20
            start_period: 10s

    api:
        container_name: gocanto-api
        restart: "always"
        build:
            context: .
            dockerfile: ./docker/Dockerfile-api
        ports:
            - "3000:3000"
        env_file:
            - .env
        depends_on:
            postgres:
                condition: service_healthy
        networks:
            - gocanto
        logging:
            driver: "json-file"
            options:
                max-file: 20
                max-size: 10M

    nginx:
        container_name: gocanto-proxy
        image: nginx:latest
        depends_on:
            - api
        volumes:
            - ./docker/nginx/hosts:/etc/hosts
            - ./docker/nginx/proxy.conf:/etc/nginx/nginx.conf:ro
        ports:
            - "80:80"
        networks:
            - gocanto

