version: "3.9"

networks:
    host:

volumes:
    database:

services:
    db:
        image: "postgres:${POSTGRES_VERSION}"
        restart: always
        env_file:
            - .env
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DATABASE}
        networks:
            - host
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./database/data:/var/lib/postgresql/data
