version: "3.9"

networks:
    api:

volumes:
    database:

services:
    db:
        image: "postgres:${POSTGRES_VERSION}"
        restart: always
        env_file:
            - .env
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DATABASE}
        networks:
            - api
        logging:
            driver: "json-file"
            options:
                max-size: "10M"
                max-file: "20"
        volumes:
            - ./database/data:/var/lib/postgresql/data
