app:
    name: gocanto
    env: APP_ENV
    log_level: APP_LOG_LEVEL

database:
    image_version: "14-alpine"
    name: DB_NAME
    user: DB_USER
    password: DB_PASS
    host: DB_HOST
    url: DB_URL
    max_lifetime: 7200
    max_open_cons: 150
    max_idle_cons: 50
