# Step 1: Modules caching
FROM golang:1.19.4-alpine3.17 AS modules
COPY go.mod go.sum /modules/
WORKDIR /modules
RUN go mod download

# Step 2: Builder
FROM golang:1.19.4-alpine3.17 AS builder
COPY --from=modules /go/pkg /go/pkg
COPY . /app
WORKDIR /app
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -tags migrate -o /bin/app ./cmd/api

# Step 3: Final
FROM scratch

EXPOSE 3000

COPY --from=builder /app/cmd/api/config.yml /
COPY --from=builder /app/database/migrations /database/migrations
COPY --from=builder /bin/app /app
CMD ["/app"]
